# Day 02 13.09.2023 {.unnumbered}

### logische Operationen

```{r}
a <- c(T, T, F, F)
b <- c(T, F, T, F)

sum(a)
sum(b)
5*a
5*b
a+b
a & b
a | b
!a | b
b | !a
!a
(a|b)+(a&b)

v <- c(160, 145, 195, 173, 181)
min(v - 150)
max(log(v - 150)) < 1
min(v - 150) > 0 && max(log(v - 150)) < 1
```

### Arbeitsblatt 3

#### Aufgabe 1

```{r}
file.path <- "C:\\Users\\oliver.speer\\Documents\\ZHAW\\imports85.txt"
imports85 <- read.table(file.path, header = T)
table(imports85$cyl, imports85$wheels)
imports85$cyl <- factor(imports85$cyl, levels = c("two", "three", "four", "five", "six", "eight", "twelve"))
prop.cyl.wheel <- round(prop.table(table(imports85$cyl, imports85$wheels)), 2)
print(prop.cyl.wheel*100)
mosaicplot(prop.cyl.wheel, color = 2:9)
barplot(prop.cyl.wheel)
barplot(prop.cyl.wheel, beside = T)

# Aufgabe 1c
# DDarstellung der Beziehung zwischen Preis und Zylinderzahl
table(imports85$price, imports85$cyl)
barplot(table(imports85$price, imports85$cyl))
plot(imports85$cyl, imports85$price)
plot(imports85$price, imports85$cyl)
plot(ecdf(imports85$price))
plot(ecdf(imports85$cyl))
plot(ecdf(imports85$city.mpg))
hist(imports85$city.mpg)
```

befehle um Tabell/Daten anzuscheun

```{r}
head(imports85)
dim(imports85)
ncol(imports85)
nrow(imports85)
colnames(imports85)
str(imports85)

```

Farben einstellen über hex code: html-color.codes oder "colors" oder im www R colors

read.table liest generisch ein, read.csv etc sind wrapper, die dann read.table aufrufen.

Working direktory

setwd() getwd()

zum löschen rm()



