# Day 04 27.09.2023 {.unnumbered}

## P-Wert

```{r}
poisson.test(x = 7, r = 4.68)
```

#### Aufgabe 2a

```{r}
poisson.test(80, 64)
```

## confidence interval

```{r}
poisson.test(x= 40)
poisson.test(x = 40, conf.level = 0.95)

```

#### Aufgabe 2b

```{r}
poisson.test(x = 8, conf.level = 0.95)
poisson.test(x = 8, conf.level = 0.975)
poisson.test(x = 8, conf.level = 0.99)

#Faustregel P2' x+2+-2(x+1)^0.5
x <- 8
x+2+c(-1,1)*2*sqrt(x+1)
#Faustregel P2 x+-2x0.5
x + c(-1,1)*2*sqrt(x)
```

#### alpha Zerfälle

```{r}
x <- 4 #pro sekunde
x + c(-1,1)*2*sqrt(x) #Faustregel P2

x <- 40 #pro 10 Sekunde
round((x + c(-1,1)*2*sqrt(x))/10, 1)

x <- 400 #pro 100 Sekunde
round((x + c(-1,1)*2*sqrt(x))/100, 1)



```

#### mit R

```{r}
poisson.test(x = 400, T = 100, conf.level = 0.95)
```

#### Hefezellen

```{r}
poisson.test(x = 1872, T = 400, conf.level = 0.95)
```

#### Aufgabe 3

```{r}
path.alpha <- "C:\\Users\\oliver.speer\\Documents\\ZHAW\\alpha.dat"
a.Zerf <- read.table(path.alpha, header = T)
m <- sum(a.Zerf$k * a.Zerf$freq)
poisson.test(x = 2612, T = m, conf.level = 0.95)
h.alpha <- rep(a.Zerf$k, a.Zerf$freq)
sum(h.alpha)
length(h.alpha)
poisson.test(x = length(h.alpha), T = sum(h.alpha), conf.level = 0.95)

```

####Aufgabe 4 HT1

```{r}
asbest23 <- read.table("C:\\Users\\oliver.speer\\Documents\\ZHAW\\asbest1.dat")
asbest52 <- read.table("C:\\Users\\oliver.speer\\Documents\\ZHAW\\asbest2.dat")
```
