# Arbeitsblatt HT1 {.unnumbered}

```{r}
path.alpha <- "alpha.dat"
a.Zerf <- read.table(path.alpha, header = T)

print(a.Zerf)

barplot(height = a.Zerf$freq, names.arg = a.Zerf$k, space = 0.5)

mean(a.Zerf$freq)

n <- sum(a.Zerf$freq)
mu <- sum(a.Zerf$k * a.Zerf$freq)/n
## Alternative Berechnung:
rep(alpha$k, alpha$freq)
mu.a <- mean(rep(alpha$k, alpha$freq))
n
mu
mu.a
```

## Wahrscheinlichkeiten mit geschätztem lambda berechnen
```{r}
yModel <- dpois(a.Zerf$k, mu)*n
yModel
yModel_wthoutn <- dpois(a.Zerf$k, mu)
yModel_wthoutn
plot(a.Zerf$k, a.Zerf$freq, type = "h", lwd = 10, col = "lightblue")
lines(a.Zerf$k, yModel, type = "b", lwd = 2, col = "navy")

```

```{r}
rpois(n=10, lambda = mu)
```

#### Aufgabe 3 Asbestfasern

#### 3a

```{r}
asbest1 <- read.table("asbest1.dat", header = F)[,1]
asbest1.ges <- read.table("asbest1.dat", header = F)
asbest1
asbest1.ges

min(asbest1)
max(asbest1)
mean(asbest1)

```

#### Spannweite

```{r}
max(asbest1) - min(asbest1)

```

#### 3b

```{r}
asbest2 <- read.table("asbest2.dat", header = F)[,1]
asbest2
min(asbest2)
max(asbest2)
mean(asbest2)
max(asbest2) - min(asbest2)
```
