# Arbeitsblatt3 {.unnumbered}

#### Aufgabe 1

```{r}
file.path <- "imports85.txt"
imports85 <- read.table(file.path, header = T)
table(imports85$cyl, imports85$wheels)
imports85$cyl <- factor(imports85$cyl, levels = c("two", "three", "four", "five", "six", "eight", "twelve"))
imports85$wheels <- factor(imports85$wheels)
table(imports85$wheels, imports85$cyl)
prop.cyl.wheel <- round(prop.table(table(imports85$wheels, imports85$cyl)), 2)
print(prop.cyl.wheel*100)
mosaicplot(prop.cyl.wheel, color = 2:9, las = 1)
mosaicplot(imports85$cyl ~ imports85$wheels, color = 1:8, las = 1)
barplot(prop.cyl.wheel)
barplot(prop.cyl.wheel, beside = T)

# Aufgabe 1c
# DDarstellung der Beziehung zwischen Preis und Zylinderzahl
table(imports85$price, imports85$cyl)
barplot(table(imports85$price, imports85$cyl))
plot(imports85$cyl, imports85$price)
plot(imports85$price, imports85$cyl)
plot(ecdf(imports85$price))
plot(ecdf(imports85$cyl))
plot(ecdf(imports85$city.mpg))
hist(imports85$city.mpg)
```

#### Aufgabe 5

```{r}
datfile <- "Erhebung_CAS_DA_HS23.rds"
dat <- readRDS(datfile)
mean(dat$fahrzeit)
median(dat$fahrzeit)
hist(dat$fahrzeit, main = "Fahrzeit (rechtsschief & unimodal)", xlab = "Fahrzeit (min)", ylab = "Häufigkeit")
abline(v = median(dat$fahrzeit), col = "red", lwd = 2)
abline(v = mean(dat$fahrzeit), col = "blue", lwd = 2)
legend("topright", col = c("red", "blue"), lwd = 2, legend = c("Median", "Mittelwert"))
```

#### Varianz, Standartabweichung, IQR, MAD

```{r}
var(dat$fahrzeit, na.rm = T)
sd(dat$fahrzeit, na.rm = T)
IQR(dat$fahrzeit, na.rm = T)
mad(dat$fahrzeit, na.rm = T)

```
