# Übungsblatt 02 {.unnumbered}
author: "Marcel Dettling"
date:   "`r Sys.Date()`"
editor: visual
lang: de
language: 
  title-block-author-single: "Autor:"
  title-block-published: "Version vom:"
format:
  html:
    embed-resources: true
    toc: true
    toc-depth: 3
    theme: sandstone
    fig-width: 8
    fig-height: 6
    fig-align: "center"
    fig-caption: true
    df-print: kable
    highlight: "monochrome"

```{css, echo = FALSE}
.justify {
  text-align: justify
}
```

## Aufgabe 1 {.justify}

```{r, echo=F, eval=T}
load("unique2010.rda")
plot(Pax ~ ATM, data=unique2010, pch=20)
```

### Teilaufgabe a)

Zeichnen sie im Scatterplot intuitiv „nach Augenmass" eine Gerade ein, die „gut zu den Daten passt", d.h. die mutmassliche Regressionsgerade.

### Teilaufgabe b)

Diskutieren sie mit ihren Nachbarn, nach welchem Kriterium sie beurteilen, bzw. beurteilt haben, ob die Gerade gut passt.

## Aufgabe 2 {.justify}

Als Schätzungen für die Regressionskoeffizienten erhalten wir durch Berechnung mit dem Kleinste-Quadrate-Algorithmus:

$\hat{\beta_1} = -138.8 ; \hat{\beta_0}=-1'197'682$

Das Ziel ist es nun, die rechnerisch bestimmte Regressionsgerade in den Scatterplot einzutragen.

### Teilaufgabe a)

Bestimmen sie den Fitted Value $\hat{y}$ für $x= 20'100$ Flugbewegungen. Wird die Paxzahl in einem Monat mit dieser Anzahl Flugbewegungen tatsächlich so gross sein? Oder anders gefragt: wie muss man den Wert $\hat{y}$ interpretieren?

### Teilaufgabe b)

Bestimmen sie den Fitted Value $\hat{y}$ nun auch für $x = 24'000$ Flugbewegungen. Wir erhalten so einen weiteren Punkt, der auf der Regressionsgerade liegt. Nun lässt sich diese einzeichnen. Vergleichen sie auch gegenüber der „von Auge" eingezeichneten Lösung auf der Vorderseite.

### Teilaufgabe c)

Berechnen sie auch noch den Fitted Value $\hat{y}$ für $x = 5'000$ Flugbewegungen. Wie stufen sie den erhaltenen Wert ein? Wie kann das passieren?

## Aufgabe 3 {.justify}

Lösen sie das [Online-Quiz](https://forms.office.com/Pages/ResponsePage.aspx?id=nZ8aXR8gEEq5g0Uc9ly8Hr0tg6Asy39BpZuXvQghN2tUMzQ1UkVHUzVBRzBQS0g1STBRTFMwVEhPVC4u) mit 8 Fragen zum Verständnis des einfachen linearen Regressionsmodells.
